version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore"
    groups:
      example:
        patterns:
        - "*"
  - package-ecosystem: "npm"
    directory: "/lib"
    commit-message:
      prefix: "fix"
    groups:
      lib:
        patterns:
        - "*"
        update-types:
        - "patch"
  - package-ecosystem: "npm"
    directory: "/lib"
    commit-message:
      prefix: "feat"
    groups:
      lib:
        patterns:
        - "*"
        update-types:
        - "major"
        - "minor"
