name: Commits

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  lint-commits:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    name: Validate Commits

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Inspect Commits
        uses: mridang/action-commit-lint@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
