name: Linting

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      commit_changes:
        required: false
        type: boolean
        default: false

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  lint-format:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Reformat Code

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci --no-progress

      - name: Run Formatter
        run: npm run format

      - name: Commit Changes
        if: ${{ inputs.commit_changes == true }}
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'style: Apply automated code formatting [skip ci]'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
