name: Pipeline

on:
  push:
    branches:
      - main
      - master
      - next
      - next-major
      - beta
      - alpha
      - '[0-9]*.x'
      - develop
      - 'release/**'
      - 'hotfix/**'
      - 'support/**'
  pull_request:

permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write

jobs:
  lint-commits:
    name: Run Commitlint Checks
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/commitlint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  code-style:
    name: Run Linter Formatter
    uses: ./.github/workflows/linting.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
      commit_changes: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets: inherit

  type-check:
    name: Run Type Checks
    uses: ./.github/workflows/typecheck.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
    secrets: inherit

  run-tests:
    name: Run Test Suite
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
    secrets: inherit

  code-inspection:
    name: Run Qodana Inspections
    needs: run-tests
    if: ${{ always() }}
    uses: ./.github/workflows/qodana.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
    secrets: inherit

  check-deps:
    name: Run Dependency Checks
    uses: ./.github/workflows/unused.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
    secrets: inherit

  all-passed:
    name: Check Build Status
    runs-on: ubuntu-latest
    if: always()
    needs:
      - lint-commits
      - code-style
      - type-check
      - run-tests
      - code-inspection
      - check-deps
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Verify all jobs passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled."
            exit 1
          fi
