name: Qodana

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      test_artifact_name:
        required: false
        type: string
        default: test-results
      coverage_artifact_name:
        required: false
        type: string
        default: test-coverage
    secrets:
      QODANA_TOKEN:
        required: true

defaults:
  run:
    working-directory: ./

jobs:
  qodana-check:
    runs-on: ubuntu-latest
    name: Inspect Code

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}

      - name: Download Test Reports Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.test_artifact_name }}
          path: ./qodana-downloaded-reports/test-results

      - name: Download Coverage Report Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.coverage_artifact_name }}
          path: ./.qodana/code-coverage

      - name: Run Qodana
        uses: JetBrains/qodana-action@f5aa2889b113c16bd6aee47817b027537ee33ac7 # v2025.1
        with:
          args: --baseline,.qodana/qodana.sarif.json
          push-fixes: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
